"""system-info add meta_data field

Revision ID: 2017dec86065
Revises: 272c89b2778d
Create Date: 2025-02-25 14:52:10.004386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2017dec86065'
down_revision = '272c89b2778d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_infos', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
